MARKETS = {
    "🇺🇸 United States (NYSE / NASDAQ)": {
        "code": "US",
        "suffix": "",
        "currency": "USD",
        "symbol": "$",
        "examples": ["AAPL", "MSFT", "GOOGL", "NVDA", "TSLA", "AMZN"],
        "description": "New York Stock Exchange & NASDAQ",
    },
    "🇬🇧 United Kingdom (LSE)": {
        "code": "GB",
        "suffix": ".L",
        "currency": "GBP",
        "symbol": "£",
        "examples": ["HSBA", "BP", "GSK", "SHEL", "AZN", "RIO"],
        "description": "London Stock Exchange",
    },
    "🇮🇳 India – NSE": {
        "code": "IN_NSE",
        "suffix": ".NS",
        "currency": "INR",
        "symbol": "₹",
        "examples": ["RELIANCE", "TCS", "INFY", "HDFCBANK", "WIPRO", "ICICIBANK"],
        "description": "National Stock Exchange of India",
    },
    "🇮🇳 India – BSE": {
        "code": "IN_BSE",
        "suffix": ".BO",
        "currency": "INR",
        "symbol": "₹",
        "examples": ["RELIANCE", "TCS", "INFY", "HDFCBANK", "LT"],
        "description": "Bombay Stock Exchange",
    },
    "🇩🇪 Germany (XETRA)": {
        "code": "DE",
        "suffix": ".DE",
        "currency": "EUR",
        "symbol": "€",
        "examples": ["SAP", "SIE", "ALV", "BMW", "BAYN", "ADS"],
        "description": "Deutsche Börse XETRA",
    },
    "🇫🇷 France (Euronext Paris)": {
        "code": "FR",
        "suffix": ".PA",
        "currency": "EUR",
        "symbol": "€",
        "examples": ["MC", "OR", "AI", "TTE", "BNP", "SAN"],
        "description": "Euronext Paris",
    },
    "🇯🇵 Japan (TSE)": {
        "code": "JP",
        "suffix": ".T",
        "currency": "JPY",
        "symbol": "¥",
        "examples": ["7203", "6758", "9984", "6861", "4063", "9432"],
        "description": "Tokyo Stock Exchange",
    },
    "🇭🇰 Hong Kong (HKEX)": {
        "code": "HK",
        "suffix": ".HK",
        "currency": "HKD",
        "symbol": "HK$",
        "examples": ["0700", "0941", "1299", "2318", "0005", "0388"],
        "description": "Hong Kong Stock Exchange",
    },
    "🇦🇺 Australia (ASX)": {
        "code": "AU",
        "suffix": ".AX",
        "currency": "AUD",
        "symbol": "A$",
        "examples": ["CBA", "BHP", "CSL", "WBC", "NAB", "ANZ"],
        "description": "Australian Securities Exchange",
    },
    "🇨🇦 Canada (TSX)": {
        "code": "CA",
        "suffix": ".TO",
        "currency": "CAD",
        "symbol": "C$",
        "examples": ["RY", "TD", "BNS", "CNR", "BAM", "SU"],
        "description": "Toronto Stock Exchange",
    },
    "🇧🇷 Brazil (B3)": {
        "code": "BR",
        "suffix": ".SA",
        "currency": "BRL",
        "symbol": "R$",
        "examples": ["PETR4", "VALE3", "ITUB4", "BBDC4", "ABEV3", "WEGE3"],
        "description": "B3 – Brasil, Bolsa, Balcão",
    },
    "🇸🇬 Singapore (SGX)": {
        "code": "SG",
        "suffix": ".SI",
        "currency": "SGD",
        "symbol": "S$",
        "examples": ["D05", "O39", "U11", "Z74", "G13", "C6L"],
        "description": "Singapore Exchange",
    },
    "🇨🇭 Switzerland (SIX)": {
        "code": "CH",
        "suffix": ".SW",
        "currency": "CHF",
        "symbol": "CHF ",
        "examples": ["NESN", "ROG", "NOVN", "AMS", "ZURN", "UHR"],
        "description": "SIX Swiss Exchange",
    },
    "🇰🇷 South Korea (KRX)": {
        "code": "KR",
        "suffix": ".KS",
        "currency": "KRW",
        "symbol": "₩",
        "examples": ["005930", "000660", "035420", "051910", "012330"],
        "description": "Korea Exchange",
    },
    "🇳🇱 Netherlands (Euronext)": {
        "code": "NL",
        "suffix": ".AS",
        "currency": "EUR",
        "symbol": "€",
        "examples": ["ASML", "HEIA", "INGA", "PHIA", "REN", "WKL"],
        "description": "Euronext Amsterdam",
    },
    "🇪🇸 Spain (BME)": {
        "code": "ES",
        "suffix": ".MC",
        "currency": "EUR",
        "symbol": "€",
        "examples": ["ITX", "SAN", "BBVA", "REP", "TEF", "IBE"],
        "description": "Bolsa de Madrid",
    },
    "🇸🇪 Sweden (Nasdaq Stockholm)": {
        "code": "SE",
        "suffix": ".ST",
        "currency": "SEK",
        "symbol": "kr",
        "examples": ["VOLV-B", "ERIC-B", "HM-B", "NDA-SE", "SEB-A", "SWED-A"],
        "description": "Nasdaq Stockholm",
    },
    "🇿🇦 South Africa (JSE)": {
        "code": "ZA",
        "suffix": ".JO",
        "currency": "ZAR",
        "symbol": "R",
        "examples": ["NPN", "SOL", "MTN", "BID", "SBK", "FSR"],
        "description": "Johannesburg Stock Exchange",
    },
}

DEFAULT_MARKETS = [
    "🇺🇸 United States (NYSE / NASDAQ)",
    "🇬🇧 United Kingdom (LSE)",
    "🇮🇳 India – NSE",
    "🇩🇪 Germany (XETRA)",
    "🇯🇵 Japan (TSE)",
]
